import type { Uuid } from '@sklv-labs/core';
import { sql } from 'drizzle-orm';
import { uuid } from 'drizzle-orm/pg-core';

/**
 * A branded uuid primary key, generated by Postgres as v7.
 *
 * v7 is time-ordered, so inserts land at the end of the index instead of scattering it the way v4
 * does. `uuidv7()` is a Postgres 18 built-in — on an older server, generate the id in the
 * application instead.
 */
export const primaryUuid = <T extends Uuid>() =>
  uuid('id')
    .primaryKey()
    .default(sql`uuidv7()`)
    .$type<T>();

/** A branded uuid reference to another table's primary key. */
export const referenceUuid = <T extends Uuid>(column: string) => uuid(column).$type<T>();
